import { KitSection, formatMeasurement } from "./KitSection.jsx";

export function PlacementPanel({ section }) {
  const map = section.mounting_map;
  const height = section.height;
  return <KitSection id="placement" section={section} title="Персональная карта высот">{map ? <><dl className="mt-5 grid border-y border-line sm:grid-cols-2 lg:grid-cols-4"><Mark label="Нижняя кромка телевизора" value={map.bottom_height_cm} /><Mark label="Центр экрана" value={map.center_height_cm} /><Mark label="Центр VESA" value={map.vesa_center_height_cm} /><Mark emphasis label="Контрольная линия настенной пластины" value={map.wall_plate_reference_height_cm} /></dl><p className="mt-4 max-w-3xl border-l-2 border-action pl-4 text-sm leading-relaxed text-muted">Линия показывает вертикальное положение пластины. Она не является точкой сверления: фактические отверстия выбирают по настенной пластине и основанию.</p></> : height ? <dl className="mt-4 grid border-y border-line sm:grid-cols-3"><Mark label="Нижняя кромка" value={height.bottom_height_cm} /><Mark label="Центр экрана" value={height.center_height_cm} /><Mark label="Верхняя кромка" value={height.top_height_cm} /></dl> : <p className="mt-4 text-muted">Введите размеры размещения, чтобы получить безопасные контрольные высоты.</p>}{section.drill_map ? <DrillMap map={section.drill_map} /> : null}</KitSection>;
}

function Mark({ emphasis = false, label, value }) { return <div className={`border-b border-line py-4 last:border-b-0 sm:px-4 lg:border-b-0 ${emphasis ? "border-l-2 border-l-action bg-surface sm:col-span-2 lg:col-span-1" : ""}`}><dt className="font-mono text-xs uppercase text-muted">{label}</dt><dd className="tabular-measure mt-1 font-display text-2xl font-extrabold">{formatMeasurement(value)}</dd></div>; }

function DrillMap({ map }) {
  return <figure className="mt-5 border border-ink bg-white p-4" data-exact-drill-map="true"><svg aria-label="Подтверждённая схема отверстий настенной пластины" className="mx-auto block h-auto max-h-[24rem] w-full" role="img" viewBox={`${-map.plate_width_mm / 2 - 20} ${-map.plate_height_mm / 2 - 20} ${map.plate_width_mm + 40} ${map.plate_height_mm + 40}`}><rect fill="none" height={map.plate_height_mm} stroke="currentColor" strokeWidth="2" width={map.plate_width_mm} x={-map.plate_width_mm / 2} y={-map.plate_height_mm / 2} />{map.hole_coordinates_mm.map((point, index) => <circle cx={point.x_mm} cy={point.y_mm} fill="#f04a0b" key={`${point.x_mm}-${point.y_mm}-${index}`} r="4" />)}<line stroke="#145a50" strokeWidth="3" x1={-map.plate_width_mm / 2} x2={-map.plate_width_mm / 2 + map.control_ruler_mm} y1={map.plate_height_mm / 2 + 10} y2={map.plate_height_mm / 2 + 10} /></svg><figcaption className="mt-3 text-sm text-muted">Масштабная схема доступна только для полностью подтверждённой геометрии. Перед сверлением измерьте контрольную линию {map.control_ruler_mm} мм.</figcaption></figure>;
}
